export default {
  FETCH_CART: "FETCH_CART",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_ERROR: "FETCH_CART_ERROR",
  ITEM_ADDED: "ITEM_ADDED",
  UPDATE_CART: "UPDATE_CART",
  CLOSE_CART_ADDED: "CLOSE_CART_ADDED",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  CLEAR_CART: "CLEAR_CART"
};
