export default {
  FETCH_USER: "FETCH_USER",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  SHOW_LOGIN: "SHOW_LOGIN",
  SHOW_REGISTER: "SHOW_REGISTER",
  HIDE_LOGIN: "HIDE_LOGIN",
  LOGIN_SUCCESS: "FETCH_USER_SUCCESS",
  LOGIN_FAILURE: "FETCH_USER_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  SET_USER: "SET_USER"
};
