export default {
  FETCH_USER: "FETCH_USER",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  SHOW_LOGIN: "SHOW_LOGIN",
  SHOW_REGISTER: "SHOW_REGISTER",
  HIDE_LOGIN: "HIDE_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  EDIT_USER: "EDIT_USER",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  ADD_ADDRESS: "ADD_ADDRESS",
  EDIT_ADDRESS: "EDIT_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS"
};
